version: "3"

services:
  mysql:
    container_name: forum_mysql
    command: --authentication_policy=mysql_native_password
    image: mysql:latest
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=${DDD_FORUM_DB_DEV_DB_NAME}
      - MYSQL_USER=${DDD_FORUM_DB_USER}
      - MYSQL_PASSWORD=${DDD_FORUM_DB_PASS}
    # networks:
    #   - forum_net

  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080
    # networks:
    #   - forum_net

  redis:
    container_name: forum_redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    # networks:
    #   - forum_net

  elasticsearch:
    container_name: forum_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: single-node
      xpack.security.enabled: false
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    # networks:
    #   - forum_net

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.8.2
  #   container_name: kibana
  #   volumes:
  #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
  #   environment:
  #     SERVER_HOST: "0.0.0.0"
  #     ELASTICSEARCH_HOSTS: "http://localhost:9200"
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - forum_net

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: always
    ports:
      - 3000:3000
      - 5550:5550
    depends_on:
      - mysql
      - redis
      - elasticsearch
    # networks:
    #   - forum_net

# networks:
#   forum_net:
#     driver: bridge

volumes:
  elastic_data:
    driver: local
  mysql_data:
    driver: local
