version: "3"

services:
  mysql:
    container_name: forum_mysql
    command: --authentication_policy=mysql_native_password
    image: mysql:latest
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=${DDD_FORUM_DB_DEV_DB_NAME}
      - MYSQL_USER=${DDD_FORUM_DB_USER}
      - MYSQL_PASSWORD=${DDD_FORUM_DB_PASS}
    networks:
      - forum_net

  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - forum_net

  redis:
    container_name: forum_redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - forum_net

  # app:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: app
  #   restart: always
  #   ports:
  #     - 3000:3000
  #     - 5550:5550
  #   depends_on:
  #     - mysql
  #     - redis
  #   volumes:
  #     - .:/usr/src/ddd/
  #     - ./docker.env:/usr/src/ddd/.env
  #   networks:
  #     - forum_net

networks:
  forum_net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
